services:
  mongo:
    image: mongo:latest
    container_name: mongo-consent
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - consent-network

  consent-api:
    build: .
    container_name: consent-api
    ports:
      - "8099:8099"
    depends_on:
      - mongo
    environment:
      SPRING_PROFILES_ACTIVE: test
    networks:
      - consent-network

networks:
  consent-network:
    driver: bridge
