version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-consent
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - consent-network

  consent-api:
    build: .
    container_name: consent-api
    ports:
      - "8099:8099"
    depends_on:
      - mongo
    environment:
      SPRING_PROFILES_ACTIVE: test
      MONGO_URI: mongodb://root:root@mongo:27017/mongo-consent?authSource=admin
    networks:
      - consent-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - consent-api
    networks:
      - consent-network

networks:
  consent-network:
    driver: bridge
