server:
  port: 8099
spring:
  application:
    name: consents
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/mongo-consent?authSource=admin

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  prometheus:
    metrics:
      export:
        enabled: true

